### ISSUE TITLE
Board is no longer available.

### ISSUE THREAD

**Issue by arturbauer** [BlueAndi/Rego6xxSrv#2]
Hi.

Unfortunately, I have discovered that the AVR-NET-IO board is no longer available. Can you recommend a similar product that would work?

Best regards

**Comment by BlueAndi** [comment]
Hi, I didn't notize that its not available anymore. My ones are still working, so it was never required for me to have a look for alternative boards.

Nowadays I would go with an esp32 board, incl. an ethernet port and one serial interface to connect the heatpump.

**Comment by BlueAndi** [comment]
Successor with Olimex esp32 board is: https://github.com/BlueAndi/IVTRego6xxControl
